#!/usr/bin/env bash

logName="$1"
logLines="$2"
optLogAll=0

for arg in "$@"
do
	if [[ "$arg" == "--all" || "$arg" == "--log-all" ]]
	then
		optLogAll=1
	fi
done

if [[ -z "$logName" || -z "$logLines" ]]
then
	echo "please provide log name and log line(s)"
	exit 1
fi

if [[ -z "$deviceName" ]]
then
	deviceName="$HOSTNAME"
fi

if [[ -z "$deviceName" || "$deviceName" == "localhost" ]] && (type hostname >/dev/null 2>&1)
then
	deviceName="$(hostname)"
fi

if [[ -z "$deviceName" || "$deviceName" == "localhost" ]]
then
	if [[ "$OSTYPE" == "linux-android" ]]
	then
		deviceName="phone"
	else
		deviceName="$OSTYPE"
	fi
fi

logPath="$HOME/.logs/$logName/${deviceName,,}_$(date +'%Y%m').log"
logDir=$(dirname "$logPath")
# dateString="$(date +'%Y%m%d,%H%M,')"
dateString="$(date +'%F,%R,')"

mkdir -p "$logDir"
touch -a "$logPath"
newRecords=0

# echo "logLines: $logLines"

# iterate over lines
while read -r logLine
do
	# only log new stuff by default
	if [[ "$optLogAll" == 1 ]] || ! grep -Fiq "$logLine" "$logDir/"*
	then
		# don't echo the date to the user
		echo "$dateString$logLine" >> "$logPath"
		echo "$logLine"
		newRecords=1
	fi
done < <( echo "$logLines" )

if [[ "$newRecords" -eq 0 ]]
then
	echo "no new items logged"
fi
