#!/usr/bin/env bash

url="$1"

if [[ -z "$url" ]]
then
	url="$("$HOME/bin/_get-test-ip")"
fi

if [[ "$OSTYPE" = "msys" ]]
then
	pingy="ping -n 1"
else
	pingy="ping -c 1"
fi

announced=0

while true
do
	if $pingy "$url" > /dev/null 2>&1
	then
		break
	fi

	if [[ "$announced" == 0 ]]
	then
		echo "waiting for a response from $url"
		announced=1
	fi

	sleep 2s
done
