#!/usr/bin/env bash

# use regex replace to support sleep syntax
# 1s, 1h, 1m, 1d etc
input=$(echo "$*" \
	| perl -pe 's/(\d+)s( |$)/\1second\2/g' \
	| perl -pe 's/(\d+)m( |$)/\1minute\2/g' \
	| perl -pe 's/(\d+)h( |$)/\1hour\2/g' \
	| perl -pe 's/(\d+)d( |$)/\1day\2/g' \
	| perl -pe 's/(\d+)d( |$)/\1week\2/g' \
)

startEpochSec=$(date +"%s")
targetEpochSec=$(date --date="$input" +"%s")
secToWait="$((targetEpochSec-startEpochSec))"

# echo "raw input: $*"
# echo "input: $input"
# echo "startEpochSec:  $startEpochSec"
# echo "targetEpochSec: $targetEpochSec"
# echo "secToWait: $secToWait"
# echo "--------"

cursorVisible() {
	# should be tput cnomr, but that disables cursor blink for some reason
	tput cvvis
	exit
}

trap cursorVisible SIGINT

tput civis

echo "sleeping til $(date --date=@"$targetEpochSec" --rfc-3339=second | cut -c -19)"


sleep "$secToWait"

cursorVisible

# TODO make this a countdown instead
# while [ "$targetEpochSec" > $(date +"%s") ]
# do
# 	echo ""
# 	sleep 1s
# done
