#!/usr/bin/env bash

set -e

scriptDir="$(dirname "$0")"
gitRoot="$(git -C "$scriptDir" rev-parse --show-toplevel)"

"$gitRoot/startup/play-boot-sound"

"$gitRoot/utilities/xscreen" wifi-log		"cd "$gitRoot" && wifi-log --loop"
"$gitRoot/utilities/xscreen" turtleradio	"cd "$gitRoot" && ./connect_and_play.sh"
"$gitRoot/utilities/xscreen" wait-push-pull	"cd "$gitRoot" && ./updates/wait-push-pull"
