#!/usr/bin/env bash

set -e

scriptDir="$(dirname "$0")"
gitRoot="$(git -C "$scriptDir" rev-parse --show-toplevel)"

# speed up boot slightly by playing the sound under a screen instance
"$gitRoot/utilities/xscreen" boot-sound "'$gitRoot/startup/play-boot-sound' && exit"

"$gitRoot/utilities/xscreen" wifi-log		"cd '$gitRoot' && ./utilities/wifi-log --loop"
"$gitRoot/utilities/xscreen" turtleradio	"cd '$gitRoot' && ./connect_and_play.sh"
"$gitRoot/utilities/xscreen" wait-push-pull	"cd '$gitRoot' && ./updates/wait-push-pull"
