#!/usr/bin/env bash

set -e

scriptDir="$(dirname "$0")"
gitRoot="$(git -C "$scriptDir" rev-parse --show-toplevel)"

# play turtle radio locally
"$gitRoot/utilities/xscreen" local-audio "'$gitRoot/startup/play-boot-sound' && '$gitRoot/utilities/aplay_turtleradio.sh'"

"$gitRoot/utilities/xscreen" wifi-log		"cd '$gitRoot' && ./utilities/wifi-log --loop"
"$gitRoot/utilities/xscreen" turtleradio	"cd '$gitRoot' && ./connect_and_play.sh"
"$gitRoot/utilities/xscreen" wait-push-pull	"cd '$gitRoot' && ./updates/wait-push-pull"
